version: "3.3"

networks:
  qk-network:
    driver: bridge

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:5.7
    container_name: poc-quarkus-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysqlDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/mysql/data
    networks:
      - qk-network